#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if package.json was changed
if git diff-tree --name-only ORIG_HEAD HEAD | grep --quiet "package.json"; then
  echo "📦 package.json changed. Installing dependencies..."
  npm install
fi

# Check if model files changed
if git diff-tree --name-only ORIG_HEAD HEAD | grep --quiet "src/models\|src/modules/.*/models"; then
  echo "🧬 Model files changed. Generating TypeScript interfaces..."
  npm run generate:types
fi

# Check if controller files changed
if git diff-tree --name-only ORIG_HEAD HEAD | grep --quiet "src/controllers\|src/modules/.*/controllers"; then
  echo "🎮 Controller files changed. Generating API types..."
  npm run generate:api-types
fi

# Run TypeScript check to ensure everything is still working
echo "🧪 Running TypeScript check..."
npm run typecheck:src